In [1]:
import pandas as pd

data = [[1, 'Wang', 'Allen'], [2, 'Alice', 'Bob']]
person = pd.DataFrame(data, columns=['personId', 'firstName', 'lastName']).astype({'personId':'Int64', 'firstName':'object', 'lastName':'object'})
data = [[1, 2, 'New York City', 'New York'], [2, 3, 'Leetcode', 'California']]
address = pd.DataFrame(data, columns=['addressId', 'personId', 'city', 'state']).astype({'addressId':'Int64', 'personId':'Int64', 'city':'object', 'state':'object'})

In [2]:
person

   personId firstName lastName
0         1      Wang    Allen
1         2     Alice      Bob

In [3]:
address

   addressId  personId           city       state
0          1         2  New York City    New York
1          2         3       Leetcode  California

In [ ]:
class Node():
    def __init__(self, data, nextnode = None):
        self.data = data
        self.nextnode = nextnode

class Linkedlist():
    def __init__(self, root = None):
        self.root = root
    def add(self, data):
        node = Node(data)
        if self.root == None:
            self.root = node
        else:
            current_node = self.root
            node.nextnode = current_node
            self.root = node
    def show(self):
        root_node = self.root
        print(root_node.data)
        while root_node.nextnode is not None:
            print(root_node.data)
            root_node = root_node.nextnode

linkedlist1 = Linkedlist()
linkedlist1.add(7)
linkedlist1.add(8)

In [20]:
linkedlist1.show()

8
8

In [ ]:
class Node():
    def __init__(self,data,adress=None):
        self.data = data
        self.adress = adress
    def get_next(self):
        return self.adress
    def get_data(self):
        return self.data
    def set_next(self, adress):
        self.adress = adress
    def set_data(self, data):
        self.data = data

class Linkedlist(object):
    def __init__(self, root = None):
        self.root = root
        self.size = 0
    def get_size(self):
        return self.size
    def add(self, data):
        new_node = Node(data, self.root)
        self.root = new_node
        self.size += 1
    def remove(self, data):
        t_node = self.root
        p_node = None
        while t_node:
            if t.node