In [20]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
d1 = pd.read_csv("data/D001/D001.csv")
d1

/var/folders/nw/yjct11rn2lq_yqyn7t95tx0w0000gn/T/ipykernel_30690/2322937767.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  d1 = pd.read_csv("data/D001/D001.csv")

,TIME_DN,KD,TE,K,NOMP,VOZR,DATE_VV,GR1,GR2,GR3,GR41,GR42,GR43,GR44,KTIME,POL,NOMER
0,05.00-05.10,1,75,2,2,22,8,931,711.0,1,1.0,NaN,3,NaN,132,1,57549
1,00.00-00.10,2,23,1,1,57,23,713,NaN,1,NaN,NaN,NaN,9.0,105,1,67154
2,12.10-12.20,1,23,1,3,18,14,921,NaN,98,NaN,NaN,NaN,NaN,31,2,67716
3,18.00-18.10,2,71,2,1,53,9,911,NaN,1,NaN,NaN,NaN,NaN,66,1,66195
4,16.20-16.30,1,63,1,2,55,17,849,NaN,97,NaN,NaN,3,NaN,56,2,24378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3431227,09.00-09.10,2,75,1,1,35,16,911,NaN,1,1.0,NaN,NaN,NaN,14,2,65111
3431228,14.00-14.10,1,43,1,1,69,21,911,NaN,1,NaN,NaN,NaN,NaN,44,2,54309
3431229,06.50-07.00,2,27,2,4,50,14,181,NaN,1,NaN,NaN,3.0,NaN,144,2,50758
3431230,02.20-02.30,2,39,2,1,68,21,842,NaN,1,NaN,NaN,NaN,9.0,118,2,61534
3431231,10.50-11.00,1,59,1,2,13,7,911,NaN,1,NaN,NaN,NaN,NaN,23,2,55377

In [23]:
d2 = pd.read_csv("data/D002/synthetic_subject_D002.csv")
d2

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR28_2,GR28_3,GR28_4,GR28_5,GR29,GR210,GR211,GR212,GR213,GR214
0,2020,15,1,1,2,48,10,6,9,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,11,1,1,2,62,10,6,9,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020,15,2,1,2,53,9,8,8,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020,61,2,1,2,22,5,9,9,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020,63,2,1,1,38,8,7,5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59702,2024,10,1,2,1,37,9,9,7,7,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
59703,2024,33,2,1,1,22,9,6,6,7,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
59704,2024,59,1,1,2,29,5,5,8,89,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
59705,2024,19,2,5,2,29,7,8,6,9,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
59706,2024,11,1,1,1,54,7,9,6,9,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,3.0,2.0

In [27]:
d2.iloc[:, range(0,50)]

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR184,GR191,GR192,GR193,GR194,GR195,GR196,GR201,GR202,GR21
0,2020,15,1,1,2,48,10,6,9,6,...,7.0,7.0,4.0,8.0,5.0,89.0,89.0,7.0,8.0,6
1,2020,11,1,1,2,62,10,6,9,8,...,89.0,89.0,7.0,10.0,7.0,8.0,8.0,89.0,10.0,7
2,2020,15,2,1,2,53,9,8,8,4,...,10.0,8.0,8.0,7.0,5.0,4.0,8.0,7.0,1.0,8
3,2020,61,2,1,2,22,5,9,9,9,...,6.0,10.0,10.0,5.0,6.0,5.0,8.0,8.0,9.0,10
4,2020,63,2,1,1,38,8,7,5,8,...,89.0,1.0,3.0,3.0,10.0,10.0,5.0,89.0,5.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59702,2024,10,1,2,1,37,9,9,7,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
59703,2024,33,2,1,1,22,9,6,6,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
59704,2024,59,1,1,2,29,5,5,8,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
59705,2024,19,2,5,2,29,7,8,6,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
59706,2024,11,1,1,1,54,7,9,6,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

In [30]:
population = pd.read_csv("data/2021_population.csv")
population.head()

/var/folders/nw/yjct11rn2lq_yqyn7t95tx0w0000gn/T/ipykernel_30690/243331555.py:1: DtypeWarning: Columns (117) have mixed types. Specify dtype option on import or set low_memory=False.
  population = pd.read_csv("data/2021_population.csv")

,MAIN,IIN,BIRTHDATE,GENDER_ID,GENDER,CITIZENSHIP_ID,CITIZENSHIP,RELATIONSHIPWITHMAIN_ID,RELATIONSHIPWITHMAIN,ADDRESS_KATO,...,KATO_BP,Q25,Q25.1.1,Q25.1.2,Q25.2,Q27.1,Q27.1.1,Q27.2,Q27.3,god
0,False,F78FAE9BB581F29965DD56A9405B8197,1986-11-15 00:00:00.000,19033970,Женский,19910034.0,Республика Казахстан,NaN,NaN,111010000,...,20244042.0,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,2021
1,False,AA6113CD8C5C0CE75DBE5D979AF4A383,2009-11-27 00:00:00.000,19033967,Мужской,19910034.0,Республика Казахстан,NaN,NaN,434067100,...,20242100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
2,False,9D6E4C3E1169AF691ECC04561C7E45A2,2011-11-28 00:00:00.000,19033967,Мужской,19910034.0,Республика Казахстан,20266980.0,NaN,791710000,...,20242100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
3,False,378351FF49071274C543B227532E89EF,1961-06-17 00:00:00.000,19033967,Мужской,19910034.0,Республика Казахстан,20266980.0,NaN,195620100,...,249639.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
4,False,8027030DD2C2E6BFE63FEFF4033D861D,1959-08-24 00:00:00.000,19033970,Женский,19910034.0,Республика Казахстан,NaN,NaN,351013100,...,265068.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2021

In [31]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 167 entries, MAIN to god
dtypes: bool(2), float64(36), int64(18), object(111)
memory usage: 126.1+ MB